version: '3.9'
services:
  dummy:
    image: busybox
    command: tail -f /dev/null
    networks:
      multility_network:
        ipv4_address: 192.168.3.2
networks:
  multility_network:
    name: multility_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24